---
info:
  title: Metasploit Data Models
  description: MSF database code, gemified
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/metasploit_data_models
  x-cortex-tag: metasploit-data-models
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
